"""New-disk wizard — pick device, fill details, generate job config."""
from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Optional

from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import Button, Footer, Header, Input, Label, ListItem, ListView, Static

from config import JOBS_DIR

# Devices that must never be selected as source
_BLOCKED = {"sda", "sdb", "sdc"}


@dataclass
class BlockDev:
    name: str
    path: str
    size_human: str
    size_bytes: int
    model: str
    serial: str
    by_path: str
    tran: str


def _list_block_devices() -> list[BlockDev]:
    try:
        r = subprocess.run(
            ["lsblk", "-d", "-b", "-J", "-o", "NAME,SIZE,MODEL,SERIAL,TRAN,TYPE"],
            capture_output=True, text=True, timeout=10,
        )
        devs: list[BlockDev] = []
        for blk in json.loads(r.stdout).get("blockdevices", []):
            if blk.get("type") != "disk":
                continue
            name = blk.get("name", "")
            size_bytes = int(blk.get("size") or 0)
            devs.append(BlockDev(
                name=name,
                path=f"/dev/{name}",
                size_human=_fmt_bytes(size_bytes),
                size_bytes=size_bytes,
                model=(blk.get("model") or "").strip(),
                serial=(blk.get("serial") or "").strip(),
                by_path=_get_by_path(name),
                tran=(blk.get("tran") or "").strip(),
            ))
        return devs
    except Exception:
        return []


def _get_by_path(devname: str) -> str:
    try:
        for link in Path("/dev/disk/by-path").iterdir():
            if link.resolve().name == devname:
                return str(link)
    except Exception:
        pass
    return ""


def _fmt_bytes(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024:
            return f"{n:.0f} {unit}"
        n //= 1024
    return f"{n} TB"


def _render_conf(
    job_name: str, date_tag: str, source_dev: str, source_by_path: str,
    source_model: str, source_serial: str, source_size_bytes: int, basename: str,
) -> str:
    size_str = str(source_size_bytes) if source_size_bytes else '""'
    # Escape { } for f-string by doubling
    return (
        f'#!/usr/bin/env bash\n'
        f'# Generated by hdd-recovery TUI wizard — {date_tag}\n\n'
        f'JOB_NAME="{job_name}"\n'
        f'DATE_TAG="{date_tag}"\n\n'
        f'SOURCE_DEV="{source_dev}"\n'
        f'SOURCE_BY_PATH="{source_by_path}"\n'
        f'SOURCE_MODEL="{source_model}"\n'
        f'SOURCE_SERIAL="{source_serial}"\n'
        f'SOURCE_SIZE_BYTES="{source_size_bytes}"\n\n'
        f'DEST_MOUNT="/mnt/recovery16tb"\n'
        f'IMAGES_DIR="$DEST_MOUNT/recovery/images"\n'
        f'LOGS_DIR="$DEST_MOUNT/recovery/logs"\n'
        f'MANIFESTS_DIR="$DEST_MOUNT/recovery/manifests"\n\n'
        f'BASENAME="{basename}"\n\n'
        f'IMAGE_FILE="$IMAGES_DIR/${{BASENAME}}.img"\n'
        f'MAP_FILE="$LOGS_DIR/${{BASENAME}}.map"\n'
        f'EVENT_LOG="$LOGS_DIR/${{BASENAME}}.events.log"\n'
        f'RATE_LOG="$LOGS_DIR/${{BASENAME}}.rates.log"\n'
        f'MANIFEST_FILE="$MANIFESTS_DIR/${{BASENAME}}.yaml"\n\n'
        f'# Conservative defaults. Adjust only with a reason.\n'
        f'RETRY_PASSES="3"\n'
        f'REVERSE_RETRY_PASSES="1"\n'
        f'RETRIM_RETRY_PASSES="1"\n'
        f'PAUSE_ON_ERROR="1s"\n'
        f'MAPFILE_INTERVAL="30s,5s"\n'
    )


class WizardScreen(Screen):
    """Guided new-disk wizard: pick device → review → generate job config."""

    BINDINGS = [
        Binding("escape", "go_back", "Cancel"),
        Binding("b", "go_back", "Cancel"),
    ]

    CSS = """
    WizardScreen { padding: 1 2; }
    #header-label { margin-bottom: 1; }
    #device-list { height: 10; border: solid $surface; margin-bottom: 1; }
    #dev-info { margin-bottom: 1; color: $text-muted; min-height: 3; }
    .field-row { height: 3; margin-bottom: 1; }
    .field-label { width: 22; padding-top: 1; }
    Input { width: 1fr; }
    #blocked-warn { color: bold red; }
    #btn-row { height: 3; margin-top: 1; }
    """

    def __init__(self) -> None:
        super().__init__()
        self._devs: list[BlockDev] = []
        self._selected: Optional[BlockDev] = None

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        yield Label("[bold]New Disk Wizard[/bold] — select source device", id="header-label")
        yield ListView(id="device-list")
        yield Static("", id="dev-info")
        yield Static("", id="blocked-warn")
        with Horizontal(classes="field-row"):
            yield Label("JOB_NAME", classes="field-label")
            yield Input(placeholder="e.g. 20250424_Seagate_ABC123_sdd", id="job-name")
        with Horizontal(classes="field-row"):
            yield Label("BASENAME", classes="field-label")
            yield Input(placeholder="e.g. 20250424_Seagate_ABC123_sdd", id="basename")
        with Horizontal(id="btn-row"):
            yield Button("Generate config", variant="primary", id="generate")
            yield Button("Cancel", id="cancel")
        yield Footer()

    def on_mount(self) -> None:
        self._load_devices()

    def _load_devices(self) -> None:
        self._devs = _list_block_devices()
        lv = self.query_one("#device-list", ListView)
        lv.clear()
        if not self._devs:
            lv.append(ListItem(Label("[dim]No block devices found.[/dim]")))
            return
        for dev in self._devs:
            blocked = dev.name in _BLOCKED
            mark = " [bold red]BLOCKED[/bold red]" if blocked else ""
            label = f"[cyan]/dev/{dev.name}[/cyan]  {dev.size_human}  {dev.model or '(no model)'}  serial={dev.serial or '?'}{mark}"
            lv.append(ListItem(Label(label)))

    def on_list_view_selected(self, event: ListView.Selected) -> None:
        idx = event.list_view.index
        if idx is None or not (0 <= idx < len(self._devs)):
            return
        dev = self._devs[idx]
        self._selected = dev

        blocked = dev.name in _BLOCKED
        warn = self.query_one("#blocked-warn", Static)
        if blocked:
            warn.update(
                f"⛔ /dev/{dev.name} is a blocked device (OS/destination/ZFS). "
                "Select a different disk."
            )
            self._selected = None
            return
        warn.update("")

        self.query_one("#dev-info", Static).update(
            f"[bold]{dev.path}[/bold]  {dev.size_human}  {dev.model}  "
            f"serial={dev.serial}  tran={dev.tran}\n"
            f"by-path: [dim]{dev.by_path or '(not found in /dev/disk/by-path)'}[/dim]"
        )

        today = date.today().strftime("%Y%m%d")
        model_clean = re.sub(r"[^A-Za-z0-9]", "", dev.model)[:20]
        serial_clean = re.sub(r"[^A-Za-z0-9]", "", dev.serial)[:12]
        suggestion = f"{today}_{model_clean}_{serial_clean}_{dev.name}"
        self.query_one("#job-name", Input).value = suggestion
        self.query_one("#basename", Input).value = suggestion

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "cancel":
            self.app.pop_screen()
        elif event.button.id == "generate":
            self._generate()

    def _generate(self) -> None:
        if not self._selected:
            self.app.notify("Select a (non-blocked) device first.", severity="warning")
            return
        job_name = self.query_one("#job-name", Input).value.strip()
        basename = self.query_one("#basename", Input).value.strip()
        if not job_name or not basename:
            self.app.notify("JOB_NAME and BASENAME are required.", severity="warning")
            return
        if not re.match(r'^[A-Za-z0-9_\-]+$', basename):
            self.app.notify(
                "BASENAME may only contain letters, digits, _ and -.",
                severity="warning",
            )
            return

        dev = self._selected
        JOBS_DIR.mkdir(parents=True, exist_ok=True)
        conf_path = JOBS_DIR / f"{basename}.conf"
        if conf_path.exists():
            self.app.notify(
                f"{conf_path.name} already exists — choose a different BASENAME.",
                severity="warning",
            )
            return

        content = _render_conf(
            job_name=job_name,
            date_tag=date.today().strftime("%Y%m%d"),
            source_dev=dev.path,
            source_by_path=dev.by_path or dev.path,
            source_model=dev.model,
            source_serial=dev.serial,
            source_size_bytes=dev.size_bytes,
            basename=basename,
        )
        conf_path.write_text(content)
        self.app.notify(
            f"Created {conf_path.name}\nReturn to dashboard — the disk will appear in the list.",
            title="Job config created",
            severity="information",
        )
        self.app.pop_screen()

    def action_go_back(self) -> None:
        self.app.pop_screen()
